### ISSUE TITLE
Overlapping issue

### ISSUE THREAD

**Issue by KiGniark** [zikes/circle-menu#9]
Hi!

I've got an issue with a component who has a z-index which is higher that the item menu. Can you make the z-index configurable so that we can choose it with an option? And i think it would be better to put a z-index equal to the value of the first item z-index -1 like below.

``` css
li:first-child{
z-index: 1000; //configurable
}
li{
z-index: 999; // first-child z-index - 1
}
```

http://codepen.io/KiGniark/pen/jPdoaE (the problem is there)

Thanks for this plugin, it's awesome!
